# Generated by Django 3.1.6 on 2021-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
