/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Book {
    'id'?: number;
    'name': string;
    'genre': BookGenreEnum;
    'releaseDate': string;
    'author': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "genre",
            "baseName": "genre",
            "type": "BookGenreEnum",
            "format": ""
        },
        {
            "name": "releaseDate",
            "baseName": "release_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Book.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type BookGenreEnum = "sci fi" | "comedy" ;

